title: lukad
author: Luka Dornhecker
email: luka@dornhecker.me
description: >-
  Personal blog where I write about random tech stuff.
baseurl: ""
url: "https://luka.dornhecker.me"
twitter_username: lukaimneuland
github_username:  lukad
lang: en

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-tidy

feed:
  path: index.xml

jekyll_tidy:
  compress_html: false
