title: lukad
author: Luka Dornhecker
email: luka@dornhecker.me
description: >-
  Personal blog where I write about random tech stuff.
baseurl: ""
url: "https://luka.dornhecker.me"
twitter_username: lukaimneuland
github_username:  lukad
lang: en
permalink: /:categories/:year/:month/:day/:title

exclude:
  - netlify.toml
  - build
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-compose
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-tidy
  - jekyll-toc

feed:
  path: index.xml

jekyll_tidy:
  compress_html: true

uncss:
  stylesheets:
    - https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css
    - assets/css/syntax.css
  files:
    - "**/*.html"
  timeout: 30
