[[headers]]
  for = "/*"
  [headers.values]
    Link = "<https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css>; rel=preload; as=style; integrity=sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm; crossorigin=anonymous"
